{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-root-app
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: "argocd"
    server: https://kubernetes.default.svc
  project: apps-project
  source:
    helm:
      releaseName: {{ .source.releaseName }}
      values: |-
        waves:
          project: 100
          rootApplication: 200
          namespace: 300
          application: 400
      valueFiles: 
        - values.yaml
    repoURL: {{ .source.url }}
    targetRevision: {{ .source.targetRevision }}
    path: {{ .source.path }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 1
{{- end }}    