kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  {{- if .Values.labels }}
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}